version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: duty_manager_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: duty_manager_backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/duties_db
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: duty_manager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: duties_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
