apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.microservice.name }}
  replicas: {{ .Values.microservice.replicas | int }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: duty-manager
        app.kubernetes.io/instance: {{ .Values.microservice.name }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: {{ .Values.workload.image }}
          envFrom:
            - configMapRef:
                name: {{ .Values.microservice.name }}-config
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.workload.port | int }}
          resources:
            requests:
              memory: {{ .Values.workload.resources.memory }}
              cpu: {{ .Values.workload.resources.cpu }}
            limits:
              memory: {{ .Values.workload.resources.memory }}
