kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.microservice.name }}-config
  namespace: {{ .Values.microservice.namespace }}
data:
  DUTY_MANAGER_FRONTEND: duty-manager-frontend
  DUTY_MANAGER_FRONTEND_HOST: frontend.localhost
  DUTY_MANAGER_FRONTEND_PORT: "3000"