services:
  frontend:
    build:
      context: ../../src/frontend
      dockerfile: Dockerfile
    container_name: duty_manager_frontend
    environment:
      - REACT_APP_DUTY_MANAGER_BACKEND=localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ../../src/backend
      dockerfile: Dockerfile
    container_name: duty_manager_backend
    ports:
      - "4000:4000"
    env_file:
      - ../../src/backend/.env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: duty_manager_postgres
    env_file:
      - ../../src/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
